# Generated by Django 4.1.3 on 2022-11-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usa',
            field=models.BooleanField(default=True, verbose_name='USA'),
        ),
        migrations.AddField(
            model_name='user',
            name='usb',
            field=models.BooleanField(default=True, verbose_name='USB'),
        ),
    ]
