# Generated by Django 4.1.3 on 2022-11-28 03:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('usa', models.BooleanField(default=True, verbose_name='USA')),
                ('usb', models.BooleanField(default=True, verbose_name='USB')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('pub_date', models.DateField(default=datetime.datetime.now, null=True)),
                ('itemUnity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.carga')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='carga',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.insumo'),
        ),
        migrations.AddField(
            model_name='carga',
            name='unity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.unidade'),
        ),
    ]
