# Generated by Django 4.1.3 on 2022-11-29 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0006_viatura_ativo_alter_registrosdiario_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosdiario',
            name='km',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrosdiario',
            name='viatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categorias.viatura'),
            preserve_default=False,
        ),
    ]
