# Generated by Django 4.1.3 on 2022-11-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0007_registrosdiario_km_registrosdiario_viatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viatura',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Viatura ativa'),
        ),
    ]
