# Generated by Django 4.1.3 on 2022-12-26 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0008_alter_viatura_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroItemDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registrosdiario',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/%d-%m-%Y', verbose_name='Pdf'),
        ),
    ]
