# Generated by Django 4.1.3 on 2022-12-26 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0009_registroitemdiario_alter_registrosdiario_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroitemdiario',
            name='carga',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroitemdiario',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categorias.insumo'),
            preserve_default=False,
        ),
    ]
