# Generated by Django 4.1.3 on 2022-12-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0010_registroitemdiario_carga_registroitemdiario_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroitemdiario',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categorias.unidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroitemdiario',
            name='vtr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categorias.viatura'),
            preserve_default=False,
        ),
    ]
