# Generated by Django 4.1.5 on 2023-04-04 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0013_alter_registroitemdiario_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroitemdiario',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.carga'),
        ),
    ]
