# Generated by Django 4.1.5 on 2023-04-04 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0014_alter_registroitemdiario_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosdiario',
            name='unity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.unidade', verbose_name='Unidade'),
        ),
    ]
