# Generated by Django 4.1.5 on 2023-04-04 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0016_alter_registrosdiario_viatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroitemdiario',
            name='vtr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.viatura'),
        ),
    ]
