# Generated by Django 4.1.5 on 2023-04-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0017_alter_registroitemdiario_vtr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroitemdiario',
            name='carga',
            field=models.CharField(max_length=15),
        ),
    ]
