# Generated by Django 4.1.5 on 2023-05-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0018_alter_registroitemdiario_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='usa',
            field=models.BooleanField(default=True, verbose_name='USA'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='usb',
            field=models.BooleanField(default=True, verbose_name='USB'),
        ),
    ]
