# Generated by Django 4.1.5 on 2023-05-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0019_insumo_usa_insumo_usb'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroitemdiario',
            name='preenchiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.registrosdiario'),
        ),
    ]
