# Generated by Django 4.1.5 on 2023-05-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0020_registroitemdiario_preenchiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroitemdiario',
            old_name='preenchiento',
            new_name='preenchimento',
        ),
    ]
