# Generated by Django 4.1.5 on 2023-05-29 14:16

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0021_rename_preenchiento_registroitemdiario_preenchimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='unitys',
            field=models.ManyToManyField(default=django.db.models.manager.BaseManager.all, to='categorias.unidade'),
        ),
    ]
