# Generated by Django 4.1.5 on 2023-05-30 13:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0022_insumo_unitys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unitys',
            field=models.ManyToManyField(default=django.db.models.manager.BaseManager.all, to='categorias.unidade'),
        ),
        migrations.AlterField(
            model_name='registrosdiario',
            name='pdf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
