# Generated by Django 4.1.5 on 2023-05-30 13:50

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0023_alter_insumo_unitys_alter_registrosdiario_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosdiario',
            name='items',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unitys',
            field=models.ManyToManyField(default=django.db.models.manager.BaseManager.all, to='categorias.unidade'),
        ),
        migrations.AlterField(
            model_name='registrosdiario',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Data'),
        ),
    ]
