# Generated by Django 4.1.5 on 2023-05-30 13:52

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0024_registrosdiario_items_alter_insumo_unitys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unitys',
            field=models.ManyToManyField(default=django.db.models.manager.BaseManager.all, to='categorias.unidade'),
        ),
        migrations.AlterField(
            model_name='registrosdiario',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
