# Generated by Django 4.1.5 on 2023-05-31 10:30

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0027_alter_insumo_unitys_delete_registroitemdiario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosdiario',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unitys',
            field=models.ManyToManyField(default=django.db.models.manager.BaseManager.all, to='categorias.unidade'),
        ),
    ]
